inherit_from:
  # - https://relaxed.ruby.style/rubocop.yml
  - .rubocop-https---relaxed-ruby-style-rubocop-yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  # disable loaded extensions manually
  # https://github.com/rubocop/rubocop/issues/9810
  SuggestExtensions:
    rubocop-rake: false
    rubocop-rspec: false
  Exclude:
    - 'bin/*'

Bundler/OrderedGems:
  Enabled: false


Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
